# Generated by Django 4.1.5 on 2024-05-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busnavigation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CET_PATTOM_EASTFORT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Route", models.CharField(max_length=200)),
                ("Stop1", models.CharField(max_length=200)),
                ("Stop2", models.CharField(max_length=200)),
                ("Stop3", models.CharField(max_length=200)),
                ("Stop4", models.CharField(max_length=200)),
                ("Stop5", models.CharField(max_length=200)),
                ("Stop6", models.CharField(max_length=200)),
                ("Stop7", models.CharField(max_length=200)),
                ("Stop8", models.CharField(max_length=200)),
                ("Stop9", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name="stops_time",
            name="Route_time",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
