# Generated by Django 4.1.5 on 2024-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busnavigation", "0002_cet_pattom_eastfort_stops_time_route_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Route", models.CharField(max_length=200)),
                ("Stop1", models.CharField(max_length=200)),
                ("Stop2", models.CharField(max_length=200)),
                ("Stop3", models.CharField(max_length=200)),
                ("Stop4", models.CharField(max_length=200)),
                ("Stop5", models.CharField(max_length=200)),
                ("Stop6", models.CharField(max_length=200)),
                ("Stop7", models.CharField(max_length=200)),
                ("Stop8", models.CharField(max_length=200)),
                ("Stop9", models.CharField(max_length=200)),
                ("Stop10", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
