# Generated by Django 4.1.5 on 2024-06-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("busnavigation", "0003_stops"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=200)),
                ("Phone_No", models.CharField(max_length=200)),
                ("Email_id", models.CharField(max_length=200)),
                ("User_Name", models.CharField(max_length=200)),
                ("Password", models.CharField(max_length=200)),
            ],
        ),
    ]
